# Generated by Django 4.0 on 2022-01-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('describe', models.CharField(max_length=256)),
                ('time', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('car_id', models.CharField(max_length=15)),
                ('car_model', models.CharField(max_length=15)),
                ('raport', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('V', 'In Progress'), ('X', 'Complete')], default='V', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('services', models.ManyToManyField(to='aso_service.Service')),
            ],
        ),
    ]
