# Generated by Django 4.0 on 2022-01-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('aso_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='machanic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.mechanic'),
            preserve_default=False,
        ),
    ]
