# Generated by Django 4.0 on 2021-12-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0002_alter_event_raport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='raport',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
