# Generated by Django 4.0 on 2022-02-15 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('aso_service', '0003_alter_event_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
