# Generated by Django 4.0 on 2022-01-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0003_alter_event_machanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='car_model',
            field=models.CharField(choices=[('X', 'Unknown'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7')], default='X', max_length=15),
        ),
    ]
