# Generated by Django 4.0 on 2021-12-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0003_alter_event_raport'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('V', 'In Progress'), ('X', 'Complete')], default='V', max_length=20),
        ),
    ]
