# Generated by Django 4.0 on 2021-12-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0004_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='worker',
        ),
    ]
