# Generated by Django 4.0 on 2022-01-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('aso_service', '0005_alter_event_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='machanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.mechanic'),
        ),
        migrations.AlterField(
            model_name='event',
            name='raport',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
