# Generated by Django 4.0 on 2022-01-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('aso_service', '0006_alter_event_machanic_alter_event_raport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='machanic',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.mechanic'),
            preserve_default=False,
        ),
    ]
