# Generated by Django 4.0 on 2022-01-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('aso_service', '0007_alter_event_machanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='machanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.mechanic'),
        ),
    ]
