# Generated by Django 4.0 on 2022-01-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0009_alter_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='machanic',
            new_name='mechanic',
        ),
    ]
