# Generated by Django 4.0 on 2022-01-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0010_rename_machanic_event_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enddate',
            field=models.DateField(default='2022-12-12'),
            preserve_default=False,
        ),
    ]
