# Generated by Django 4.0 on 2022-01-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0011_event_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='enddate',
            field=models.DateField(null=True),
        ),
    ]
