# Generated by Django 4.0 on 2022-01-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0012_alter_event_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ttd',
            field=models.IntegerField(null=True),
        ),
    ]
