# Generated by Django 4.0 on 2022-01-17 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('aso_service', '0013_event_ttd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.mechanic'),
        ),
    ]
