# Generated by Django 4.0 on 2022-01-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0015_alter_event_enddate_alter_event_ttd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ttd',
            field=models.IntegerField(default=0),
        ),
    ]
