# Generated by Django 4.0 on 2022-01-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0020_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
