# Generated by Django 4.0 on 2022-01-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0021_alter_position_end_time_alter_position_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aso_service.position'),
        ),
    ]
