# Generated by Django 4.0 on 2022-01-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0022_event_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ttd',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.TimeField(),
        ),
    ]
