# Generated by Django 4.0 on 2022-01-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0023_alter_event_ttd_alter_service_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ttd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.IntegerField(),
        ),
    ]
