# Generated by Django 4.0 on 2022-01-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0024_alter_event_ttd_alter_service_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
