# Generated by Django 4.0 on 2022-01-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0026_alter_position_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='Station',
        ),
    ]
