# Generated by Django 4.0 on 2022-01-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0027_rename_position_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='position',
            new_name='station',
        ),
    ]
