# Generated by Django 4.0 on 2021-12-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_service', '0003_alter_event_raport'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='completed_events',
            field=models.ManyToManyField(to='aso_service.Event'),
        ),
    ]
