# Generated by Django 4.0 on 2021-12-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mechanic_completed_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='surname',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
