# Generated by Django 4.0 on 2021-12-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_name_customer_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='pesel',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='manager',
            name='surname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='surname',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
